FROM bellsoft/liberica-openjdk-alpine:11.0.10

COPY ./java ./src
RUN mkdir ./out
RUN javac -sourcepath ./src -d out src/ru/geekbrains/Java_Core_HW_1/sample/Main.java
CMD java -classpath ./out ru.geekbrains.Java_Core_HW_1.sample.Main